extends: "semantic-release-monorepo"
repositoryUrl: https://github.com/gsmlg-dev/Foundation
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - - "@semantic-release/exec"
    - "prepareCmd" : >-
        echo ${nextRelease.version};
        mkdir -p build;
        export LDFLAGS="-ldflags '-w -s -X github.com/gsmlg-dev/Foundation/golang/gsmlg-cli/cmd.version=${nextRelease.version}'" ;
        GOOS=linux GOARCH=amd64 go build \${LDFLAGS} -o build/gsmlg-cli_linux_amd64 main.go ;
        GOOS=windows GOARCH=amd64 go build \${LDFLAGS} -o build/gsmlg-cli_amd64.exe main.go ;
        GOOS=darwin GOARCH=amd64 go build \${LDFLAGS} -o build/gsmlg-cli_mac_amd64 main.go ;
        GOOS=freebsd GOARCH=amd64 go build \${LDFLAGS} -o build/gsmlg-cli_freebsd_amd64 main.go ;
        GOOS=linux GOARCH=arm64 go build \${LDFLAGS} -o build/gsmlg-cli_linux_arm64 main.go ;
        GOOS=windows GOARCH=arm64 go build \${LDFLAGS} -o build/gsmlg-cli_arm64.exe main.go ;
        GOOS=darwin GOARCH=arm64 go build \${LDFLAGS} -o build/gsmlg-cli_mac_arm64 main.go ;
      "publishCmd" : "echo pubhlish gsmlg-cli ${nextRelease.version}"
branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - main
  - next
  - next-major
  - {name: 'beta', prerelease: true}
  - {name: 'alpha', prerelease: true}
