extends: "semantic-release-monorepo"
repositoryUrl: https://github.com/gsmlg/Foundation
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - - "@semantic-release/exec"
    - "prepareCmd" : >-
        echo ${nextRelease.version};
        mkdir -p build;
        GOOS=linux GOARCH=amd64 go build -o build/hash_linux_amd64 cmd/hashdir.go ;
        GOOS=windows GOARCH=amd64 go build -o build/hash_amd64.exe cmd/hashdir.go ;
        GOOS=darwin GOARCH=amd64 go build -o build/hash_mac_amd64 cmd/hashdir.go ;
        GOOS=linux GOARCH=arm64 go build -o build/hash_linux_arm64 cmd/hashdir.go ;
        GOOS=windows GOARCH=arm64 go build -o build/hash_arm64.exe cmd/hashdir.go ;
        GOOS=darwin GOARCH=arm64 go build -o build/hash_mac_arm64 cmd/hashdir.go ;
      "publishCmd" : "echo pubhlish hashdir ${nextRelease.version} ; ls build"
branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - main
  - next
  - next-major
  - {name: 'beta', prerelease: true}
  - {name: 'alpha', prerelease: true}
