extends: "semantic-release-monorepo"
release:
  repositoryUrl: https://github.com/gsmlg/Foundation
  plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/npm'
    - - '@semantic-release/github'
      - assets: 
          - path: "build/**"
            name: Phoenix-Provider
            label: phoenix-provider
branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - main
  - next
  - next-major
  - {name: 'beta', prerelease: true}
  - {name: 'alpha', prerelease: true}