extends: "semantic-release-monorepo"
repositoryUrl: https://github.com/gsmlg-dev/Foundation.git
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - "@semantic-release/exec"
    - "prepareCmd" : "echo ${nextRelease.version}"
      "publishCmd" : |
        cat <<EOF
        Publish caddy release at
        https://github.com/gsmlg-dev/Foundation/releases/tag/caddy-v${nextRelease.version}
        EOF
  - '@semantic-release/github'
branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - main
  - next
  - next-major
  - {name: 'beta', prerelease: true}
  - {name: 'alpha', prerelease: true}
