[package]
name = "chat"
version = "0.1.0"
authors = ["Jonathan Gao <gsmlg.com@gmail.com>"]
edition = "2018"

[dependencies]
term = "*"
rustyline = "*"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking"] }
