---

all:
  children:
    # Master group, do not change the 'master' name
    # hosts should match the filenames in 'host_vars'
    master:
      hosts:
        k8s-master:
    # Worker group, do not change the 'worker' name
    # hosts should match the filenames in 'host_vars'
    worker:
      hosts:
        k8s-worker-a:
        k8s-worker-b:
        k8s-worker-c:
        k8s-worker-d:
        k8s-worker-e:
    # Storage group, these are my NAS devices
    # hosts should match the filenames in 'host_vars'
    storage:
      hosts:
        nas-rocinante:
        nas-serenity:
