---

- include: host.yml
  tags:
  - host

- include: time.yml
  tags:
  - time

- include: packages.yml
  tags:
  - packages

- include: power-button.yml
  tags:
  - power-button

- include: motd.yml
  tags:
  - motd

- include: kernel.yml
  tags:
  - kernel

- include: network.yml
  tags:
  - network

- include: filesystem.yml
  tags:
  - filesystem

- include: unattended-upgrades.yml
  tags:
  - unattended-upgrades

- include: user.yml
  tags:
  - user

- include: rsyslog.yml
  when:
  - rsyslog.enabled is defined
  - rsyslog.enabled
  tags:
  - rsyslog
