---

- name: packages | disable recommends
  become: true
  copy:
    content: |
      APT::Install-Recommends "false";
      APT::Install-Suggests "false";
      APT::Get::Install-Recommends "false";
      APT::Get::Install-Suggests "false";
    dest: /etc/apt/apt.conf.d/02norecommends

- name: packages | upgrade all packages
  apt:
    upgrade: full
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success

- name: packages | install common
  become: true
  apt:
    name: "{{ packages.apt_install }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success
  when:
  - packages.apt_install is defined
  - packages.apt_install is iterable
  - packages.apt_install | length > 0

- name: packages | gather install packages
  package_facts:
    manager: auto
  when:
  - packages.apt_remove is defined
  - packages.apt_remove is iterable
  - packages.apt_remove | length > 0
  - "'snapd' in packages.apt_remove"

# Until focal has https://launchpad.net/ubuntu/+source/htop
- name: packages | install latest htop
  become: true
  apt:
    deb: "https://launchpad.net/ubuntu/+archive/primary/+files/htop_{{ packages.deb.htop_version | default('3.0.2-1') }}_amd64.deb"
  register: apt_install_htop
  retries: 5
  until: apt_install_htop is success
  when:
  - "'htop' not in ansible_facts.packages"
  - "'htop' not in packages.apt_install"
  - packages.deb.htop_version is defined
  - packages.deb.htop_version

- name: packages | check if snap is installed
  debug:
    msg: "snapd is installed"
  register: snapd_check
  when:
  - "'snapd' in ansible_facts.packages"
  - packages.apt_remove is defined
  - packages.apt_remove is iterable
  - packages.apt_remove | length > 0
  - "'snapd' in packages.apt_remove"

- name: packages | remove snap packages
  become: true
  command: snap remove {{ item }}
  loop:
  - lxd
  - core18
  - snapd
  when:
  - ansible_distribution == 'Ubuntu'
  - snapd_check.failed is defined
  - packages.apt_remove is defined
  - packages.apt_remove is iterable
  - packages.apt_remove | length > 0
  - "'snapd' in packages.apt_remove"

- name: packages | remove packages
  become: true
  apt:
    name: "{{ packages.apt_remove }}"
    state: absent
    autoremove: true
  when:
  - packages.apt_remove is defined
  - packages.apt_remove is iterable
  - packages.apt_remove | length > 0

- name: packages | remove file and directory cruft
  become: true
  file:
    state: absent
    path: "{{ item }}"
  loop:
  - "/home/{{ ansible_user }}/.snap"
  - "/snap"
  - "/var/snap"
  - "/var/lib/snapd"
  - "/var/cache/snapd"
  - "/usr/lib/snapd"
  - "/etc/cloud"
  - "/var/lib/cloud"
  when:
  - packages.apt_remove is defined
  - packages.apt_remove is iterable
  - packages.apt_remove | length > 0
  - "'snapd' in packages.apt_remove"
  - "'cloud-init' in packages.apt_remove"
