---

- hosts:
  - master
  - worker
  become: true
  gather_facts: true
  vars_prompt:
    - name: "restart_confirmation"
      prompt: "Restart nodes when complete? [Y/n]"
      default: "n"
      private: no
  roles:
  - os
  tasks:
  - name: os-prepare | reboot
    ignore_errors: true
    reboot:
      msg: "Nodes are being rebooted..."
    when: restart_confirmation == "Y"
    tags:
    - always
