ARG ELIXIR_VERSION="1.16"
FROM elixir:${ELIXIR_VERSION}-alpine

ARG PHOENIX_VERSION="1.7.10"

LABEL maintainer="Jonathan Gao <gsmlg.com@gmail.com>"

LABEL ELIXIR_VERSION="${ELIXIR_VERSION}"
LABEL PHOENIX_VERSION="${PHOENIX_VERSION}"

RUN mix local.rebar --force
RUN mix local.hex --force
RUN mix archive.install --force hex phx_new ${PHOENIX_VERSION}

RUN apk --force-broken-world --no-cache add make bash figlet curl git nodejs npm

ENTRYPOINT ["/bin/bash", "-c"]
