FROM elixir:1.12.3

ARG PHOENIX_VERSION="1.5"

LABEL mantainer="GSMLG <gsmlg.com@gmail.com>"

LABEL PHOENIX_VERSION="${PHOENIX_VERSION}"

RUN apt-get update \
    && apt-get install -y make \
    && mix local.rebar --force \
    && mix local.hex --force \
    && mix archive.install --force hex phx_new ${PHOENIX_VERSION} \
    && apt-get clean


ENTRYPOINT ["/bin/bash"]
