# This is a basic workflow to help you get started with Actions

name: Build Docker Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ elixir ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        # The name of the image you would like to push
        name: gsmlg/gsmlg.org
        # The login username for the registry
        username: ${{ secrets.DOCKERHUB_USER }}
        # The login password for the registry
        password: ${{ secrets.DOCKERHUB_PASSWD }}
        # Use registry for pushing to a custom registry
        # registry: # optional
        # Use snapshot to push an additional image
        # snapshot: # optional
        # Use dockerfile when you would like to explicitly build a Dockerfile
        # dockerfile: # optional
        # Use workdir when you would like to change the directory for building
        # workdir: # optional
        # Use buildargs when you want to pass a list of environment variables as build-args
        # buildargs: # optional
        # Use cache when you have big images, that you would only like to build partially
        # cache: # optional
        # Use tag_names when you want to push tags/release by their git name
        # tag_names: # optional
        # Push semver docker tags. e.g. image:1.2.3, image:1.2, image:1
        # tag_semver: # optional

