name: docker-buildimage-baidupcs-go

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'The version of the alpine'
        default: 'v3.9.7'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'qjfoidnh/BaiduPCS-Go'
          ref: ${{ github.event.inputs.version }}
          path: 'docker/baidupcs-go/src'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: docker/baidupcs-go/
          file: docker/baidupcs-go/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            GO111MODULE=on
            VERSION=${{ github.event.inputs.version }}
          tags: |
            ghcr.io/gsmlg-dev/baidupcs-go:${{ github.event.inputs.version }}
            ghcr.io/gsmlg-dev/baidupcs-go:latest
