name: docker-buildimage-meshcentral

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/meshcentral/**'
      - '.github/workflows/docker-buildimage-meshcentral.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      -
        name: Set build date
        id: build-date
        run: |
          echo "ym=$(date +%Y-%m)" >> $GITHUB_OUTPUT
          echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/meshcentral/
          file: docker/meshcentral/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            MESHCENTRAL2_VERSION=1.1.22
          tags: |
            docker.io/gsmlg/meshcentral:1.1.22
            docker.io/gsmlg/meshcentral:latest

