name: docker-buildimage-rabbitmq

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/rabbitmq/**'
      - '.github/workflows/docker-buildimage-rabbitmq.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker/rabbitmq/
          file: docker/rabbitmq/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: gsmlg/rabbitmq:latest

