name: docker-buildimage-baidupcs-go

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/baidupcs-go/**'
      - '.github/workflows/docker-buildimage-baidupcs-go.yml'

jobs:
  build-image:
    strategy:
      matrix:
        version: ["v3.8.7"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'qjfoidnh/BaiduPCS-Go'
          ref: ${{ matrix.version }}
          path: 'docker/baidupcs-go/src'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: docker/baidupcs-go/
          file: docker/baidupcs-go/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            docker.io/gsmlg/baidupcs-go:${{ matrix.version }}
            docker.io/gsmlg/baidupcs-go:latest
