name: docker-buildimage-caddy

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/caddy/**'
      - '.github/workflows/docker-buildimage-caddy.yml'

jobs:
  sematic-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: 🚀 Release
        uses: gsmlg/semantic-release-action@v3
        id: semantic
        with:
          release_name: caddy
          working-directory: docker/caddy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  build-package:
    runs-on: ubuntu-latest
    needs: [ sematic-version ]
    strategy:
      matrix:
        platforms:
          - os: linux
            arch: amd64
          - os: darwin
            arch: amd64
          - os: freebsd
            arch: amd64
          - os: windows
            arch: amd64
          - os: linux
            arch: arm64
          - os: android
            arch: arm64
          - os: darwin
            arch: arm64
          - os: windows
            arch: arm64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - run: go version
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - 
        env:
          GOOS: ${{ matrix.platforms.os }}
          GOARCH: ${{ matrix.platforms.arch }}
          USER: gsmlg
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |-
          echo "machine github.com login ${USER} password ${TOKEN}" > $HOME/.netrc ;
          xcaddy build v2.4.6 \
            --output caddy_${GOOS}_${GOARCH} \
            --with github.com/mholt/caddy-l4 \
            --with github.com/caddy-dns/cloudflare \
            --with github.com/mholt/caddy-webdav \
            --with github.com/caddy-dns/route53 \
            --with github.com/gsmlg-dev/caddy-dns-zdns \
            --with github.com/greenpau/caddy-auth-portal
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: caddy_${{ matrix.platforms.os }}_${{ matrix.platforms.arch }}
          asset_name: caddy_${{ matrix.platforms.os }}_${{ matrix.platforms.arch }}
          tag: caddy-v${{ needs.sematic-version.outputs.version }}
  build-image:
    runs-on: ubuntu-latest
    needs: [ sematic-version ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: docker/caddy/
          file: docker/caddy/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            CADDY_VERSION=2.4.6
            USER=gsmlg
            TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tags: |
            docker.io/gsmlg/caddy:v${{ needs.sematic-version.outputs.version }}
            docker.io/gsmlg/caddy:latest

