name: docker-buildimage-caddy

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/caddy/**'
      - '.github/workflows/docker-buildimage-caddy.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: 🚀 Release
        uses: gsmlg/semantic-release-action@v3
        id: semantic
        with:
          release_name: caddy
          working-directory: docker/caddy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/caddy/
          file: docker/caddy/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            CADDY_VERSION=2.4.6
          tags: |
            docker.io/gsmlg/caddy:v${{ steps.semantic.outputs.new_release_version }}
            docker.io/gsmlg/caddy:latest

