name: docker-buildimage-antlr

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/antlr/**'
      - '.github/workflows/docker-buildimage-antlr.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/antlr/
          file: docker/antlr/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            docker.io/gsmlg/antlr:latest
            ghcr.io/gsmlg-dev/antlr:latest

