name: docker-buildimage-phoenix

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/phoenix/**'
      - '.github/workflows/docker-buildimage-phoenix.yml'

jobs:
  build-image:
    strategy:
      matrix:
        type:
          - base: "latest"
            platforms: linux/amd64,linux/arm64
            tag: 1.7.18
          - base: "alpine"
            platforms: linux/amd64,linux/arm64
            tag: 1.7.18-alpine
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/phoenix/
          file: docker/phoenix/Dockerfile.${{ matrix.type.base }}
          platforms: ${{ matrix.type.platforms }}
          push: true
          build-args: |
            ELIXIR_VERSION=1.17
            PHOENIX_VERSION=1.7.18
          tags: |
            docker.io/gsmlg/phoenix:${{ matrix.type.tag }}
            docker.io/gsmlg/phoenix:${{ matrix.type.base }}
            ghcr.io/gsmlg-dev/phoenix:${{ matrix.type.tag }}
            ghcr.io/gsmlg-dev/phoenix:${{ matrix.type.base }}
