name: docker-buildimage-mariadb

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/mariadb/**'
      - '.github/workflows/docker-buildimage-mariadb.yml'

jobs:
  build-image:
    strategy:
      matrix:
        version: ["10.7", "10.8", "10.9"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/mariadb/
          file: docker/mariadb/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            MARIADB_VERSION=${{ matrix.version }}
          tags: |
            docker.io/gsmlg/mariadb:v${{ matrix.version }}
