name: docker-buildimage-code-server

on:
  schedule:
    - cron: '0 8 * * 0'
  push:
    branches: [ main ]
    paths:
      - 'docker/code-server/**'
      - '.github/workflows/docker-buildimage-code-server.yml'

jobs:
  get-latest-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-latest-version.outputs.version }}
    steps:
      -
        name: Get latest version
        id: get-latest-version
        run: |
          version=$(curl -sSLf https://api.github.com/repos/coder/code-server/releases/latest | jq -r .name | cut -c 2-)
          echo "version=$version" | tee -a $GITHUB_OUTPUT
  build-code-server-image:
    needs: get-latest-version
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Set build date
        id: build-date
        run: |
          echo "ym=$(date +%Y-%m)" >> $GITHUB_OUTPUT
          echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/code-server/
          file: docker/code-server/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            VERSION=${{ needs.get-latest-version.outputs.version }}
            BUILD_DATE=${{ steps.build-date.outputs.date }}
          tags: |
            ghcr.io/gsmlg-dev/code-server:v${{ needs.get-latest-version.outputs.version }}
            ghcr.io/gsmlg-dev/code-server:latest
            docker.io/gsmlg/code-server:v${{ needs.get-latest-version.outputs.version }}
            docker.io/gsmlg/code-server:latest
