name: docker-buildimage-code-server

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/code-server/**'
      - '.github/workflows/docker-buildimage-code-server.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      -
        name: Set build date
        id: build-date
        run: |
          echo "ym=$(date +%Y-%m)" >> $GITHUB_OUTPUT
          echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/code-server/
          file: docker/code-server/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            VERSION=4.93.1
            BUILD_DATE=${{ steps.build-date.outputs.date }}
          tags: |
            ghcr.io/gsmlg-dev/code-server:v4.93.1
            ghcr.io/gsmlg-dev/code-server:latest
            docker.io/gsmlg/code-server:v4.93.1
            docker.io/gsmlg/code-server:latest
