name: docker-buildimage-python

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/python/**'
      - '.github/workflows/docker-buildimage-python.yml'

jobs:
  build-image:
    strategy:
      matrix:
        version:
          - "3.4"
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker/python/
          file: docker/python/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
          tags: |
            gsmlg/python:v${{ matrix.version }}

