name: docker-buildimage-semantic-release

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/semantic-release/**'
      - '.github/workflows/docker-buildimage-semantic-release.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/semantic-release/
          file: docker/semantic-release/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: gsmlg/semantic-release:latest
      -
        name: Build and push node-18
        uses: docker/build-push-action@v5
        with:
          context: docker/semantic-release/
          file: docker/semantic-release/Dockerfile.node18
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: gsmlg/semantic-release:node-18

