name: docker-buildimage-varnish

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/varnish/**'
      - '.github/workflows/docker-buildimage-varnish.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/varnish/
          file: docker/varnish/Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          push: true
          tags: gsmlg/varnish:latest

