name: docker-buildimage-couch-alpine

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/couch-alpine/**'
      - '.github/workflows/docker-buildimage-couch-alpine.yml'

jobs:
  build-couch-alpine-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64/v8
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/couch-alpine/
          file: docker/couch-alpine/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            VERSION=3.4.2
          tags: |
            docker.io/gsmlg/couchdb:alpine
            ghcr.io/gsmlg-dev/couchdb:alpine

