name: docker-buildimage-nginx

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/nginx/**'
      - '.github/workflows/docker-buildimage-nginx.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      -
        name: Login to DockerHub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build alpine and push
        uses: docker/build-push-action@v6
        with:
          context: docker/nginx/
          file: docker/nginx/Dockerfile
          platforms: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          push: true
          tags: gsmlg/nginx:latest
      -
        name: Build debian and push
        uses: docker/build-push-action@v6
        with:
          context: docker/nginx/
          file: docker/nginx/Dockerfile.debian
          platforms: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          push: true
          tags: gsmlg/nginx:debian
