name: docker-buildimage-kubectl

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/kubectl/**'
      - '.github/workflows/docker-buildimage-kubectl.yml'

jobs:
  build-image:
    strategy:
      matrix:
        version:
          - 1.27.0
          - 1.27.1
          - 1.27.2
          - 1.27.3
          - 1.27.4
          - 1.27.5
          - 1.27.6
          - 1.27.7
          - 1.27.8
          - 1.27.9
          - 1.27.10
          - 1.27.11
          - 1.27.12
          - 1.27.13
          - 1.27.14
          - 1.28.0
          - 1.28.1
          - 1.28.2
          - 1.28.3
          - 1.28.4
          - 1.28.5
          - 1.28.6
          - 1.28.7
          - 1.28.8
          - 1.28.9
          - 1.28.10
          - 1.29.0
          - 1.29.1
          - 1.29.2
          - 1.29.3
          - 1.29.4
          - 1.29.5
          - 1.30.0
          - 1.30.1
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/kubectl/
          file: docker/kubectl/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            KUBE_VERSION=${{ matrix.version }}
          tags: |
            docker.io/gsmlg/kubectl:v${{ matrix.version }}
            ghcr.io/gsmlg-dev/kubectl:v${{ matrix.version }}


