name: docker-buildimage-daedalos

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ main ]
    paths:
      - 'docker/daedalos/**'
      - '.github/workflows/docker-buildimage-daedalos.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'DustinBrett/daedalOS'
          ref: main
          path: 'daedalos/'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: daedalos/
          file: docker/daedalos/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            docker.io/gsmlg/daedalos:latest
            ghcr.io/gsmlg-dev/daedalos:latest


