name: docker-buildimage-phoenix

on:
  workflow_dispatch:
    inputs:
      elixir-version:
        required: true
        description: 'The version of the elixir'
        default: '1.18.4'
      phoenix-version:
        required: true
        description: 'The version of the phoenix'
        default: '1.7.21'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/phoenix/
          file: docker/phoenix/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ELIXIR_VERSION=${{ github.event.inputs.elixir-version }}
            PHOENIX_VERSION=${{ github.event.inputs.phoenix-version }}
          tags: |
            docker.io/gsmlg/phoenix:${{ github.event.inputs.phoenix-version }}
            docker.io/gsmlg/phoenix:latest
            ghcr.io/gsmlg-dev/phoenix:${{ github.event.inputs.phoenix-version }}
            ghcr.io/gsmlg-dev/phoenix:latest
      -
        name: Build and push alpine
        uses: docker/build-push-action@v5
        with:
          context: docker/phoenix/
          file: docker/phoenix/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ELIXIR_VERSION=${{ github.event.inputs.elixir-version }}
            PHOENIX_VERSION=${{ github.event.inputs.phoenix-version }}
          tags: |
            docker.io/gsmlg/phoenix:${{ github.event.inputs.phoenix-version }}-alpine
            docker.io/gsmlg/phoenix:alpine
            ghcr.io/gsmlg-dev/phoenix:${{ github.event.inputs.phoenix-version }}-alpine
            ghcr.io/gsmlg-dev/phoenix:alpine
