name: docker-buildimage-phoenix

on:
  push:
    branches: main
    paths:
      - 'docker/phoenix/**'
      - '.github/workflows/docker-buildimage-phoenix.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/phoenix/
          file: docker/phoenix//Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          build-args: |
            PHOENIX_VERSION=1.5.12
          tags: |
            docker.io/gsmlg/phoenix:1.5.12
            docker.io/gsmlg/phoenix:latest
      -
        name: Build and push slim
        uses: docker/build-push-action@v2
        with:
          context: docker/phoenix/
          file: docker/phoenix//Dockerfile.slim
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          build-args: |
            PHOENIX_VERSION=1.5.12
          tags: |
            docker.io/gsmlg/phoenix:1.5.12-slim
            docker.io/gsmlg/phoenix:slim
      -
        name: Build and push alpine
        uses: docker/build-push-action@v2
        with:
          context: docker/phoenix/
          file: docker/phoenix//Dockerfile.alpine
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          build-args: |
            PHOENIX_VERSION=1.5.12
          tags: |
            docker.io/gsmlg/phoenix:1.5.12-alpine
            docker.io/gsmlg/phoenix:alpine
