name: docker-buildimage-baidupcs-go

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/baidupcs-go/**'
      - '.github/workflows/docker-buildimage-baidupcs-go.yml'

jobs:
  build-image:
    strategy:
      matrix:
        version:
          - v3.9.5
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'qjfoidnh/BaiduPCS-Go'
          ref: ${{ matrix.version }}
          path: 'docker/baidupcs-go/src'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: docker/baidupcs-go/
          file: docker/baidupcs-go/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            GO111MODULE=on
            VERSION=${{ matrix.version }}
          tags: |
            ghcr.io/gsmlg-dev/baidupcs-go:${{ matrix.version }}
            ghcr.io/gsmlg-dev/baidupcs-go:latest
