name: docker-buildimage-code-server

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/code-server/**'
      - '.github/workflows/docker-buildimage-code-server.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker/code-server/
          file: docker/code-server/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            VERSION=4.12.0
          tags: |
            ghcr.io/gsmlg/code-server:v4.12.0
            ghcr.io/gsmlg/code-server:latest

