name: docker-buildimage-parse-server

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/parse-server/**'
      - '.github/workflows/docker-buildimage-parse-server.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      version: '5.2.1'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'parse-community/parse-server'
          ref: ${{ outputs.version }}
          path: 'parse-server'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: parse-server/
          file: parse-server/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            VERSION=${{ outputs.version }}
          tags: |
            docker.io/gsmlg/parse-server:v${{ outputs.version }}
            docker.io/gsmlg/parse-server:latest

