name: docker-buildimage-python

on:
  schedule:
    - cron: '0 4 1 * *'
  push:
    branches: [ main ]
    paths:
      - 'docker/python/**'
      - '.github/workflows/docker-buildimage-python.yml'

jobs:
  build-image:
    strategy:
      matrix:
        version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13-rc"
          - "3"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Set build date
        id: build-date
        run: |
          echo "ym=$(date +%Y-%m)" >> $GITHUB_OUTPUT
          echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/python/
          file: docker/python/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
          tags: |
            docker.io/gsmlg/python:v${{ matrix.version }}
            ghcr.io/gsmlg-dev/python:v${{ matrix.version }}

