name: docker-buildimage-squid

on:
  push:
    branches: master
    paths:
      - 'docker/squid/**'
      - '.github/workflows/docker-buildimage-squid.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/squid/
          file: docker/squid//Dockerfile
          platforms: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          push: true
          tags: gsmlg/squid:latest

