name: docker-buildimage-zerotier

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/zerotier/**'
      - '.github/workflows/docker-buildimage-zerotier.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/zerotier/
          file: docker/zerotier/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            ALPINE_IMAGE=alpine
            ALPINE_VERSION=3.16
            ZT_COMMIT=651f45fe29155c462f4e56dd74f4a347f6861d0d
            ZT_VERSION=1.10.1
          tags: |
            docker.io/gsmlg/zerotier:v1.10.1
            docker.io/gsmlg/zerotier:latest
            ghcr.io/gsmlg-dev/zerotier:v1.10.1
            ghcr.io/gsmlg-dev/zerotier:latest
