name: docker-buildimage-parse-server

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/parse-server/**'
      - '.github/workflows/docker-buildimage-parse-server.yml'

jobs:
  build-image:
    strategy:
      matrix:
        version: ["5.2.1"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'parse-community/parse-server'
          ref: ${{ matrix.version }}
          path: 'parse-server'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: parse-server/
          file: parse-server/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            docker.io/gsmlg/parse-server:v${{ matrix.version }}
            docker.io/gsmlg/parse-server:latest
