name: docker-buildimage-zerotier-ui

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/zerotier-ui/**'
      - '.github/workflows/docker-buildimage-zerotier-ui.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/zerotier-ui/
          file: docker/zerotier-ui/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            ARG ZT_UI_COMMIT=00592d9ad498c2ddb0569def3d65aff88773e55f
            ARG ZT_UI_VERSION=1.5.8
          tags: |
            docker.io/gsmlg/zerotier-ui:v1.5.8
            docker.io/gsmlg/zerotier-ui:latest
            ghcr.io/gsmlg-dev/zerotier-ui:v1.5.8
            ghcr.io/gsmlg-dev/zerotier-ui:latest
