name: docker-buildimage-kubectl

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/kubectl/**'
      - '.github/workflows/docker-buildimage-kubectl.yml'

jobs:
  build-image:
    strategy:
      matrix:
        version:
          - 1.22.1
          - 1.22.2
          - 1.22.3
          - 1.22.4
          - 1.22.5
          - 1.22.6
          - 1.22.7
          - 1.22.8
          - 1.22.9
          - 1.22.10
          - 1.22.11
          - 1.22.12
          - 1.22.13
          - 1.23.1
          - 1.23.2
          - 1.23.3
          - 1.23.4
          - 1.23.5
          - 1.23.6
          - 1.23.7
          - 1.23.8
          - 1.23.9
          - 1.23.10
          - 1.24.1
          - 1.24.2
          - 1.24.3
          - 1.24.4
          - 1.25.0
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/kubectl/
          file: docker/kubectl/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            KUBE_VERSION=${{ matrix.version }}
          tags: |
            gsmlg/kubectl:v${{ matrix.version }}

