name: docker-buildimage-zerotier

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'The version of the zerotier'
        default: '1.14.2'
      git-ref:
        required: true
        description: 'The git-ref of the zerotier'
        default: '1.14.2'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/zerotier/
          file: docker/zerotier/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            ZT_COMMIT=${{ github.event.inputs.git-ref }}
            ZT_VERSION=${{ github.event.inputs.version }}
          tags: |
            docker.io/gsmlg/zerotier:${{ github.event.inputs.version }}
            docker.io/gsmlg/zerotier:latest
            ghcr.io/gsmlg-dev/zerotier:${{ github.event.inputs.version }}
            ghcr.io/gsmlg-dev/zerotier:latest
