name: docker-buildimage-daedalos

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/daedalos/**'
      - '.github/workflows/docker-buildimage-daedalos.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'DustinBrett/daedalOS'
          ref: main
          path: 'docker/daedalos/'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker/daedalos/
          file: docker/daedalos/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: gsmlg/daedalos:latest

