name: docker-buildimage-phoenix

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/phoenix/**'
      - '.github/workflows/docker-buildimage-phoenix.yml'

jobs:
  build-image:
    strategy:
      matrix:
        type:
          - base: "latest"
            platforms: linux/amd64
            tag: 1.6.12
          - base: "alpine"
            platforms: linux/amd64
            tag: 1.6.12-alpine
          - base: "slim"
            platforms: linux/amd64
            tag: 1.6.12-slim
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/phoenix/
          file: docker/phoenix/Dockerfile.${{ matrix.type }}
          platforms: ${{ matrix.type.platforms }}
          push: true
          build-args: |
            ELIXIR_VERSION=1.14.0
            PHOENIX_VERSION=1.6.12
          tags: |
            docker.io/gsmlg/phoenix:${{ matrix.type.tag }}
            docker.io/gsmlg/phoenix:${{ matrix.type.base }}
