name: docker-buildimage-kubectl

on:
  push:
    branches: main
    paths:
      - 'docker/kubectl/**'
      - '.github/workflows/docker-buildimage-kubectl.yml'

jobs:
  build-image:
    strategy:
      matrix:
        version:
          - 1.20
          - 1.20.1
          - 1.20.2
          - 1.20.3
          - 1.20.4
          - 1.20.5
          - 1.20.6
          - 1.20.7
          - 1.20.8
          - 1.20.9
          - 1.20.10
          - 1.21
          - 1.21.1
          - 1.21.2
          - 1.21.3
          - 1.21.4
          - 1.22
          - 1.22.1
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/kubectl/
          file: docker/kubectl//Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            KUBE_VERSION=${{ matrix.version }}
          tags: |
            gsmlg/kubectl:v${{ matrix.version }}

