name: docker-buildimage-alpine

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'The version of the alpine'
        default: 'latest'

jobs:
  build-alpine-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/alpine/
          file: docker/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            ALPINE_VERSION=${{ github.event.inputs.version }}
          tags: |
            docker.io/gsmlg/alpine:${{ github.event.inputs.version }}
            ghcr.io/gsmlg-dev/alpine:${{ github.event.inputs.version }}

