name: docker-buildimage-meshcentral

on:
  schedule:
    - cron: '0 8 5 * *'
  push:
    branches: [ main ]
    paths:
      - 'docker/meshcentral/**'
      - '.github/workflows/docker-buildimage-meshcentral.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: ⚙️ Install deps
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y curl jq
      -
        name: Get latest version
        id: get-version
        run: |
          TOKEN=${{ secrets.GHCR_TOKEN }}
          OUT=$(curl -sSL https://api.github.com/repos/Ylianst/MeshCentral/releases/latest \
            --header "Authorization: Bearer $TOKEN" \
            --header "X-GitHub-Api-Version: 2022-11-28")
          VERSION=$(echo $OUT | jq -r '.name')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      -
        name: Set build date
        id: build-date
        run: |
          echo "ym=$(date +%Y-%m)" >> $GITHUB_OUTPUT
          echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/meshcentral/
          file: docker/meshcentral/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            MESHCENTRAL2_VERSION=${{ steps.get-version.outputs.version }}
            BUILD_DATE=${{ steps.build-date.outputs.date }}
          tags: |
            docker.io/gsmlg/meshcentral:${{ steps.get-version.outputs.version }}
            docker.io/gsmlg/meshcentral:latest
            ghcr.io/gsmlg-dev/meshcentral:${{ steps.get-version.outputs.version }}
            ghcr.io/gsmlg-dev/meshcentral:latest


