name: docker-buildimage-zerotier-ui

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/zerotier-ui/**'
      - '.github/workflows/docker-buildimage-zerotier-ui.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/zerotier-ui/
          file: docker/zerotier-ui/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            ARG ZT_UI_COMMIT=d6f05af126bd879da886ea23a42de995fcb22309
            ARG ZT_UI_VERSION=1.5.0
          tags: |
            gsmlg/zerotier-ui:v1.5.0
            gsmlg/zerotier-ui:latest

