name: docker-buildimage-dell-openmanage

on:
  push:
    branches: [ main ]
    paths:
      - "docker/dell-openmanage/**"
      - ".github/workflows/docker-buildimage-dell-openmanage.yml"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/dell-openmanage/
          file: docker/dell-openmanage/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/gsmlg/dell-openmanage:v9.5.0
            docker.io/gsmlg/dell-openmanage:latest
