name: docker-buildimage-stunnel

on:
  push:
    branches: master
    paths:
      - 'docker/stunnel/**'
      - '.github/workflows/docker-buildimage-stunnel.yml'

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/stunnel/
          file: docker/stunnel//Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armv7
          push: true
          tags: gsmlg/stunnel:latest

