name: docker-buildimage-mariadb

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/mariadb/**'
      - '.github/workflows/docker-buildimage-mariadb.yml'

jobs:
  build-image:
    strategy:
      matrix:
        version:
          - ver: 10.11.10
            tag: 10
          - ver: 11.7.1
            tag: 11

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/mariadb/
          file: docker/mariadb/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            MARIADB_VERSION=${{ matrix.version.ver }}
          tags: |
            docker.io/gsmlg/mariadb:${{ matrix.version.tag }}
            ghcr.io/gsmlg-dev/mariadb:${{ matrix.version.tag }}
