name: docker-buildimage-rabbitmq

on:
  schedule:
    - cron: '0 8 1 * *'
  push:
    branches: [ main ]
    paths:
      - 'docker/rabbitmq/**'
      - '.github/workflows/docker-buildimage-rabbitmq.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Set build date
        id: build-date
        run: |
          echo "ym=$(date +%Y-%m)" >> $GITHUB_OUTPUT
          echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/rabbitmq/
          file: docker/rabbitmq/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            docker.io/gsmlg/rabbitmq:${{ steps.build-date.outputs.ym }}
            ghcr.io/gsmlg-dev/rabbitmq:${{ steps.build-date.outputs.ym }}
            docker.io/gsmlg/rabbitmq:latest
            ghcr.io/gsmlg-dev/rabbitmq:latest

