name: elixir-gsmlg-build-and-release
on:
  push:
    paths:
      - "elixir/gsmlg/**"
      - "elixir/gsmlg_umbrella/**"
      - ".github/workflows/elixir-gsmlg-build-and-release.yml"
    branches:
      - "main"
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🚀 Release
        uses: gsmlg/semantic-release-action@v3
        id: semantic
        with:
          release_name: gsmlg
          working-directory: 'elixir/gsmlg_umbrella'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: elixir/gsmlg_umbrella
          file: elixir/gsmlg_umbrella/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            RELEASE_VERSION=${{ steps.semantic.outputs.new_release_version }}
          tags: |
            docker.io/gsmlg/gsmlg.org:v${{ steps.semantic.outputs.new_release_version }}
            docker.io/gsmlg/gsmlg.org:latest

      - name: Setup Elixir
        uses: erlef/setup-beam@v1

      - name: Run build
        run: |
          cd elixir/gsmlg_umbrella
          mix do deps.get, compile
          cd apps/gsmlg_web
          npm install --prefix assets
          mix assets.deploy
          cd ../..
          curl -Lf $(npm info --json @gsmlg/website | jq -r .dist.tarball) -o website.tgz
          tar xzf website.tgz --strip-components=2 -C apps/gsmlg_web/priv/static
          mix release gsmlg_umbrella
          cp -r _build/prod/rel/gsmlg_umbrella gsmlg
          tar zcf gsmlg.tar.gz gsmlg

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: elixir/gsmlg_umbrella/gsmlg.tar.gz
          asset_name: gsmlg_umbrella
          tag: ${{ github.ref }}
          overwrite: true
          body: "GSMLG Elixir Phoenix APP"
