name: golang-dingding-oapi-release
on:
  push:
    paths:
      - "golang/dingding-oapi/**"
      - ".github/workflows/golang-dingding-oapi-release.yml"
    branches:
      - "main"
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🚀 Release
        uses: gsmlg/semantic-release-action@v3
        with:
          release_name: dingding-oapi
          working-directory: 'golang/dingding-oapi'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

