name: nodejs-lit-validate-and-release
on:
  push:
    paths:
      - 'nodejs/packages/lit/**'
      - '.github/workflows/nodejs-lit-validate-and-release.yml'
    branches:
      - 'main'
jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          working-directory: 'nodejs/packages/lit'

      - name: ▶️ Run validate script
        working-directory: 'nodejs/packages/lit'
        run: npm run validate

  release:
    needs: main
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'gsmlg-dev/Foundation' && contains('refs/heads/main',github.ref) && github.event_name == 'push' }}
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 🪓 Remove Workspace package.json
        working-directory: 'nodejs'
        run: rm package.json

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          working-directory: 'nodejs/packages/lit'

      - name: 🏗 Run build script
        working-directory: 'nodejs/packages/lit'
        run: npm run build

      - name: 🏗 Run install semantic-release
        working-directory: 'nodejs/packages/lit'
        run: npm install --save-dev semantic-release-monorepo semantic-release

      - name: 🚀 Release
        working-directory: 'nodejs/packages/lit'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --extends semantic-release-monorepo
